summarizer:
  provider: gemini
  llm: 
    model: models/gemini-1.5-flash
    temperature: 0.8

search: 
  max_results: 1
  search_depth: basic                     # [basic, advanced] for relevant search.
  include_answer: True                    # Include a list of query related images in the response
  include_images: False                   # Include a short answer to original query in the search results
  include_raw_content: False              # Include cleaned and parsed HTML of each site search results

wipe_db: 
  host: localhost
  port: 6379
  decode_responses: True

pubsub: 
  topic: ai-trends
  partition: 0
  num_records_consume: 1                   # num_records_consume <= search['max_results']