 
summarizer:
  provider: gemini
  llm: 
    model: models/gemini-1.5-flash
    temperature: 0.8

search: 
  max_results: 5
  search_depth: basic                     # [basic, advanced] for relevant search.
  include_answer: True                    # Include a list of query related images in the response
  include_images: False                   # Include a short answer to original query in the search results
  include_raw_content: False              # Include cleaned and parsed HTML of each site search results
